### PR TITLE
modified code to regex search for xml

### PR DESCRIPTION
**Pull request by smromain**
#30 modified main JS, as well as minified JS as well

### CODE REVIEW

**Comment by johngeorgewright** [comment]
Thanks. Can we have a test to show the original problem?

**Comment by smromain** [comment]
Sure. I'll upload my test spec later this afternoon.

**Comment by smromain** [comment]
Unit test has been added. Unfortunately, wasn't completely able to replicate E2E, due to some ChromeDriver issues I'm still working through.

**Comment by johngeorgewright** [comment]
Don't worry about the e2e tests. The unit test is fine. Thanks!

**Pull request merged**
